var jslintOptions = {
/*
    anon      : true,
    bitwise   : true,
    browser   : true,
    cap       : true,
    'continue': true,
    css       : true,
    debug     : true,
    devel     : true,
    eqeq      : true,
    es5       : true,
    evil      : true,
    forin     : true,
    fragment  : true,
    indent    :   10,
    maxerr    : 1000,
    maxlen    :  256,
    newcap    : true,
    node      : true,
    nomen     : true,
    on        : true,
    passfail  : true,
    plusplus  : true,
    properties: true,
    regexp    : true,
    rhino     : true,
    undef     : true,
    unparam   : true,
    sloppy    : true,
    sub       : true,
    vars      : true,
    white     : true,
    widget    : true,
    windows   : true
*/
};
